# Combining Data Sets
> Combining datasets: **concat** and **append**  
> Combining datasets: **merge** and **join**   
> How to join? Columns, index?

In [1]:
import pandas as pd
import numpy as np

## Concatenation of NumPy Arrays

In [2]:
x = [1, 2, 3]
y = [4, 5, 6]
z = [7, 8, 9]
np.concatenate([x, y, z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
x = [[1, 2],[3, 4]]
np.concatenate([x, x], axis=1)

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

## Concatenation of Pandas Series

In [4]:
ser1 = pd.Series(['A', 'B', 'C'], index=[1, 2, 3])
ser2 = pd.Series(['D', 'E', 'F'], index=[4, 5, 6])
pd.concat([ser1, ser2])

1    A
2    B
3    C
4    D
5    E
6    F
dtype: object

In [5]:
a = np.array(range(4)).reshape((2,2))
b = np.array(range(4,8)).reshape((2,2))

print(a)
print('------------------------')
print(b)

[[0 1]
 [2 3]]
------------------------
[[4 5]
 [6 7]]


In [6]:
df1 = pd.DataFrame(a,columns=list('AB'))
df2 = pd.DataFrame(b,columns=list('AB'))

print(df1)
print('------------------------')
print(df2)
print('------------------------')
print(pd.concat([df1, df2]))

   A  B
0  0  1
1  2  3
------------------------
   A  B
0  4  5
1  6  7
------------------------
   A  B
0  0  1
1  2  3
0  4  5
1  6  7


In [7]:
print(df1.append(df2)) # Does NOT modify df1 in-place
print('------------------------')
print(df1)

   A  B
0  0  1
1  2  3
0  4  5
1  6  7
------------------------
   A  B
0  0  1
1  2  3


In [8]:
df3 = pd.DataFrame(a,columns=list('AB'))
df4 = pd.DataFrame(b,columns=list('CD'))

print(df3)
print('------------------------')
print(df4)
print('------------------------')
print(pd.concat([df3, df4], axis=1))

   A  B
0  0  1
1  2  3
------------------------
   C  D
0  4  5
1  6  7
------------------------
   A  B  C  D
0  0  1  4  5
1  2  3  6  7


In [9]:
df5 = pd.DataFrame(a,columns=list('AB'), index=[0, 1])
df6 = pd.DataFrame(b,columns=list('AB'), index=[0, 1])

print(pd.concat([df5, df6], ignore_index=True))
print('------------------------')
print(pd.concat([df5, df6], keys=['x', 'y']))

   A  B
0  0  1
1  2  3
2  4  5
3  6  7
------------------------
     A  B
x 0  0  1
  1  2  3
y 0  4  5
  1  6  7


## Joining Datasets with Common Variables

In [11]:
c = np.array(range(6)).reshape((2,3))
d = np.array(range(6,12)).reshape((2,3))

df7 = pd.DataFrame(c,columns=list('ABC'), index=[1,2])
df8 = pd.DataFrame(d,columns=list('BCD'), index=[3,4])

print(df7)
print('------------------------')
print(df8)
print('------------------------')
print(pd.concat([df7, df8]))
print('------------------------')
print(pd.concat([df7, df8], join='inner'))
print('------------------------')


   A  B  C
1  0  1  2
2  3  4  5
------------------------
   B   C   D
3  6   7   8
4  9  10  11
------------------------
     A  B   C     D
1  0.0  1   2   NaN
2  3.0  4   5   NaN
3  NaN  6   7   8.0
4  NaN  9  10  11.0
------------------------
   B   C
1  1   2
2  4   5
3  6   7
4  9  10
------------------------


## Merge Datasets
> Note the difference between **concat** and **merge**.  

In [12]:
df1 = pd.DataFrame({'employee': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'group': ['Accounting', 'Engineering', 'Engineering', 'HR']})
df2 = pd.DataFrame({'employee': ['Lisa', 'Bob', 'Jake', 'Sue'],
                    'hire_date': [2004, 2008, 2012, 2014]})

print(df1)
print('------------------------')
print(df2)

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR
------------------------
  employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014


In [13]:
pd.concat([df1, df2],axis=1)

employee        group employee  hire_date
0      Bob   Accounting     Lisa       2004
1     Jake  Engineering      Bob       2008
2     Lisa  Engineering     Jake       2012
3      Sue           HR      Sue       2014

In [14]:
# Automatically merge by common variable "employee"
df3 = pd.merge(df1, df2)
df3

employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

In [15]:
pd.merge(df1, df2, on='employee')

employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

In [16]:
# 'name' has the same role as 'employee' but different variable name!

df3 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'salary': [70000, 80000, 120000, 90000]})
df3

name  salary
0   Bob   70000
1  Jake   80000
2  Lisa  120000
3   Sue   90000

In [17]:
pd.merge(df1, df3, left_on="employee", right_on="name")

employee        group  name  salary
0      Bob   Accounting   Bob   70000
1     Jake  Engineering  Jake   80000
2     Lisa  Engineering  Lisa  120000
3      Sue           HR   Sue   90000

In [18]:
pd.merge(df1, df3, left_on="employee", right_on="name").drop('name',axis=1)

employee        group  salary
0      Bob   Accounting   70000
1     Jake  Engineering   80000
2     Lisa  Engineering  120000
3      Sue           HR   90000

In [19]:
df3.rename(columns={'name':'employee'},inplace=True)
pd.merge(df1,df3)

employee        group  salary
0      Bob   Accounting   70000
1     Jake  Engineering   80000
2     Lisa  Engineering  120000
3      Sue           HR   90000

In [20]:
df1a = df1.set_index('employee')
df2a = df2.set_index('employee')
print(df1a)
print('------------------------')
print(df2a)

                group
employee             
Bob        Accounting
Jake      Engineering
Lisa      Engineering
Sue                HR
------------------------
          hire_date
employee           
Lisa           2004
Bob            2008
Jake           2012
Sue            2014


In [21]:
pd.merge(df1a, df2a, left_index=True, right_index=True)

group  hire_date
employee                        
Bob        Accounting       2008
Jake      Engineering       2012
Lisa      Engineering       2004
Sue                HR       2014

In [22]:
df1a.join(df2a)

group  hire_date
employee                        
Bob        Accounting       2008
Jake      Engineering       2012
Lisa      Engineering       2004
Sue                HR       2014

### Many-to-one joins

In [23]:
df3 = pd.merge(df1,df2)
df4 = pd.DataFrame({'group': ['Accounting', 'Engineering', 'HR'],
                    'supervisor': ['Carly', 'Guido', 'Steve']})
print(df3)
print('------------------------')
print(df4)
print('------------------------')
print(pd.merge(df3, df4))

  employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014
------------------------
         group supervisor
0   Accounting      Carly
1  Engineering      Guido
2           HR      Steve
------------------------
  employee        group  hire_date supervisor
0      Bob   Accounting       2008      Carly
1     Jake  Engineering       2012      Guido
2     Lisa  Engineering       2004      Guido
3      Sue           HR       2014      Steve


### Many-to-many joins

In [24]:
df5 = pd.DataFrame({'group': ['Accounting', 'Accounting','Engineering', 
                              'Engineering', 'HR', 'HR'],
                    'skills': ['math', 'spreadsheets', 'coding', 
                               'linux','spreadsheets', 'organization']})
print(df1)
print('------------------------')
print(df5)
print('------------------------')
print(pd.merge(df1, df5))

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR
------------------------
         group        skills
0   Accounting          math
1   Accounting  spreadsheets
2  Engineering        coding
3  Engineering         linux
4           HR  spreadsheets
5           HR  organization
------------------------
  employee        group        skills
0      Bob   Accounting          math
1      Bob   Accounting  spreadsheets
2     Jake  Engineering        coding
3     Jake  Engineering         linux
4     Lisa  Engineering        coding
5     Lisa  Engineering         linux
6      Sue           HR  spreadsheets
7      Sue           HR  organization


### Not every observation match

In [25]:
df6 = pd.DataFrame({'name': ['Peter', 'Paul', 'Mary'],
                    'food': ['fish', 'beans', 'bread']},
                   columns=['name', 'food'])
df7 = pd.DataFrame({'name': ['Mary', 'Joseph'],
                    'drink': ['wine', 'beer']},
                   columns=['name', 'drink'])
print(df6)
print('------------------------')
print(df7)
print('------------------------')
print(pd.merge(df6, df7))

    name   food
0  Peter   fish
1   Paul  beans
2   Mary  bread
------------------------
     name drink
0    Mary  wine
1  Joseph  beer
------------------------
   name   food drink
0  Mary  bread  wine


In [26]:
pd.merge(df6, df7, how='inner')

name   food drink
0  Mary  bread  wine

In [27]:
pd.merge(df6, df7, how='outer')

name   food drink
0   Peter   fish   NaN
1    Paul  beans   NaN
2    Mary  bread  wine
3  Joseph    NaN  beer

In [28]:
pd.merge(df6, df7, how='left')

name   food drink
0  Peter   fish   NaN
1   Paul  beans   NaN
2   Mary  bread  wine

### Overlapping Column Names

In [29]:
df8 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'rank': [1, 2, 3, 4]})
df9 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'rank': [3, 1, 4, 2]})
pd.merge(df8, df9, on="name")

name  rank_x  rank_y
0   Bob       1       3
1  Jake       2       1
2  Lisa       3       4
3   Sue       4       2

In [30]:
pd.merge(df8, df9, on="name", suffixes=["_L", "_R"])

name  rank_L  rank_R
0   Bob       1       3
1  Jake       2       1
2  Lisa       3       4
3   Sue       4       2

# Example on Data Preparation: US States Data

In [31]:
!curl -O https://raw.githubusercontent.com/jakevdp/data-USstates/master/state-population.csv

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 57935  100 57935    0     0   116k      0 --:--:-- --:--:-- --:--:--  116k


In [32]:
pop = pd.read_csv('state-population.csv')
pop.head()

state/region     ages  year  population
0           AL  under18  2012   1117489.0
1           AL    total  2012   4817528.0
2           AL  under18  2010   1130966.0
3           AL    total  2010   4785570.0
4           AL  under18  2011   1125763.0

In [33]:
!curl -O https://raw.githubusercontent.com/jakevdp/data-USstates/master/state-areas.csv

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   835  100   835    0     0   1950      0 --:--:-- --:--:-- --:--:--  1950


In [34]:
areas = pd.read_csv('state-areas.csv')
areas.head()

state  area (sq. mi)
0     Alabama          52423
1      Alaska         656425
2     Arizona         114006
3    Arkansas          53182
4  California         163707

In [35]:
!curl -O https://raw.githubusercontent.com/jakevdp/data-USstates/master/state-abbrevs.csv

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   872  100   872    0     0   2169      0 --:--:-- --:--:-- --:--:--  2174


In [36]:
abbrevs = pd.read_csv('state-abbrevs.csv')
abbrevs.head()

state abbreviation
0     Alabama           AL
1      Alaska           AK
2     Arizona           AZ
3    Arkansas           AR
4  California           CA

## Merge Data Sets of States Abbreviation

In [37]:
pop_ab = pd.merge(pop, abbrevs, how='outer',
                  left_on='state/region', 
                  right_on='abbreviation')
pop_ab.head()

state/region     ages  year  population    state abbreviation
0           AL  under18  2012   1117489.0  Alabama           AL
1           AL    total  2012   4817528.0  Alabama           AL
2           AL  under18  2010   1130966.0  Alabama           AL
3           AL    total  2010   4785570.0  Alabama           AL
4           AL  under18  2011   1125763.0  Alabama           AL

In [38]:
pop_ab = pop_ab.drop('abbreviation',axis=1) 
pop_ab.head()

state/region     ages  year  population    state
0           AL  under18  2012   1117489.0  Alabama
1           AL    total  2012   4817528.0  Alabama
2           AL  under18  2010   1130966.0  Alabama
3           AL    total  2010   4785570.0  Alabama
4           AL  under18  2011   1125763.0  Alabama

## Fill in Missing Values for States

In [39]:
pop_ab.isnull().any()

state/region    False
ages            False
year            False
population       True
state            True
dtype: bool

In [40]:
pop_ab[pop_ab['state'].isnull()].head()

state/region     ages  year  population state
2448           PR  under18  1990         NaN   NaN
2449           PR    total  1990         NaN   NaN
2450           PR    total  1991         NaN   NaN
2451           PR  under18  1991         NaN   NaN
2452           PR    total  1993         NaN   NaN

In [41]:
# Choose ALL null rows, and column 'state/region'. Read its unique values.
pop_ab.loc[pop_ab['state'].isnull(), 'state/region'].unique()

array(['PR', 'USA'], dtype=object)

In [42]:
# data.loc[row condition, variable_to_be_updated] = 'new value'

pop_ab.loc[pop_ab['state/region'] == 'PR', 'state'] = 'Puerto Rico'
pop_ab.loc[pop_ab['state/region'] == 'USA', 'state'] = 'United States'

pop_ab.isnull().any()

state/region    False
ages            False
year            False
population       True
state           False
dtype: bool

### Merge the 3rd Dataset

In [43]:
final = pd.merge(pop_ab, areas, on='state', how='left')
final.head()

state/region     ages  year  population    state  area (sq. mi)
0           AL  under18  2012   1117489.0  Alabama        52423.0
1           AL    total  2012   4817528.0  Alabama        52423.0
2           AL  under18  2010   1130966.0  Alabama        52423.0
3           AL    total  2010   4785570.0  Alabama        52423.0
4           AL  under18  2011   1125763.0  Alabama        52423.0

In [44]:
final.isnull().any()

state/region     False
ages             False
year             False
population        True
state            False
area (sq. mi)     True
dtype: bool

In [45]:
final.dropna(inplace=True)
final.head()

state/region     ages  year  population    state  area (sq. mi)
0           AL  under18  2012   1117489.0  Alabama        52423.0
1           AL    total  2012   4817528.0  Alabama        52423.0
2           AL  under18  2010   1130966.0  Alabama        52423.0
3           AL    total  2010   4785570.0  Alabama        52423.0
4           AL  under18  2011   1125763.0  Alabama        52423.0

## Subsetting the Data

In [46]:
data2010 = final.query(" year == 2010 & ages == 'total' ")
data2010.head()

state/region   ages  year  population       state  area (sq. mi)
3             AL  total  2010   4785570.0     Alabama        52423.0
91            AK  total  2010    713868.0      Alaska       656425.0
101           AZ  total  2010   6408790.0     Arizona       114006.0
189           AR  total  2010   2922280.0    Arkansas        53182.0
197           CA  total  2010  37333601.0  California       163707.0

## Creating New Variables

In [47]:
data2010.set_index('state', inplace=True) 

In [48]:
data2010['density'] = data2010['population'] / data2010['area (sq. mi)']
data2010.head()

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


state/region   ages  year  population  area (sq. mi)     density
state                                                                      
Alabama              AL  total  2010   4785570.0        52423.0   91.287603
Alaska               AK  total  2010    713868.0       656425.0    1.087509
Arizona              AZ  total  2010   6408790.0       114006.0   56.214497
Arkansas             AR  total  2010   2922280.0        53182.0   54.948667
California           CA  total  2010  37333601.0       163707.0  228.051342

## Activity 1
> Generate 2 data sets using the following codes.  
```python
d1 = {'Customer_id':pd.Series([1,2,3,4,5,6]),
      'Product':pd.Series(['Oven','Oven','Oven','Television','Television','Television'])}
d2 = {'Customer_id':pd.Series([2,4,6]),
    'State':pd.Series(['California','California','Texas'])}
```
> 1. Convert them into **pandas dataframe**.  
> 2. Merge ```d1``` and ```d2``` using **inner**, **outer**, **left** and **right** and compare. 

In [49]:
d1 = {'Customer_id':pd.Series([1,2,3,4,5,6]),
      'Product':pd.Series(['Oven','Oven','Oven','Television','Television','Television'])}
df1 = pd.DataFrame(d1)
df1

Customer_id     Product
0            1        Oven
1            2        Oven
2            3        Oven
3            4  Television
4            5  Television
5            6  Television

In [50]:
d2 = {'Customer_id':pd.Series([2,4,6]),
    'State':pd.Series(['California','California','Texas'])}
df2 = pd.DataFrame(d2)
df2

Customer_id       State
0            2  California
1            4  California
2            6       Texas

In [51]:
pd.merge(df1, df2, on='Customer_id', how='inner')

Customer_id     Product       State
0            2        Oven  California
1            4  Television  California
2            6  Television       Texas

In [52]:
pd.merge(df1, df2, on='Customer_id', how='outer')

Customer_id     Product       State
0            1        Oven         NaN
1            2        Oven  California
2            3        Oven         NaN
3            4  Television  California
4            5  Television         NaN
5            6  Television       Texas

In [53]:
pd.merge(df1, df2, on='Customer_id', how='left')

Customer_id     Product       State
0            1        Oven         NaN
1            2        Oven  California
2            3        Oven         NaN
3            4  Television  California
4            5  Television         NaN
5            6  Television       Texas

In [54]:
pd.merge(df1, df2, on='Customer_id', how='right')

Customer_id     Product       State
0            2        Oven  California
1            4  Television  California
2            6  Television       Texas